import Link from "next/link";
import { ArrowRight, BookOpenCheck, Clock3, GraduationCap } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

export const metadata={title:"Lộ trình của tôi"};
export default async function MyCourses(){
  const user=await requireUser();
  const enrollments=await db.enrollment.findMany({where:{userId:user.id,status:{in:["ACTIVE","COMPLETED"]}},include:{course:{include:{sections:{include:{lessons:{select:{id:true,title:true}}}}}}},orderBy:{enrolledAt:"desc"}});
  const all=await Promise.all(enrollments.map(async e=>{const ids=e.course.sections.flatMap(s=>s.lessons.map(l=>l.id));const completed=await db.lessonProgress.count({where:{userId:user.id,lessonId:{in:ids},completed:true}});return{...e,total:ids.length,completed,percent:ids.length?Math.round(completed*100/ids.length):0}}));
  return <main className="app-shell"><section className="page-hero"><div className="container"><p className="eyebrow" style={{color:"#6ee7b7"}}>Không gian học tập</p><h1>Chào {user.name.split(" ").slice(-1)},<br/>tiếp tục tiến về phía trước.</h1><p style={{color:"#b8d2c8"}}>Mọi bước tiến nhỏ hôm nay đều góp phần tạo nên lợi thế dài hạn.</p></div></section><section className="section" style={{paddingTop:55}}><div className="container"><div className="section-head"><div><p className="eyebrow">Lộ trình đang sở hữu</p><h2 className="section-title" style={{fontSize:38}}>Khóa học của tôi</h2></div><Link href="/courses" className="btn btn-outline">Khám phá thêm <ArrowRight size={16}/></Link></div><div style={{display:"grid",gap:20}}>{all.length===0?<div className="card" style={{padding:55,textAlign:"center"}}><span className="icon-box" style={{margin:"0 auto"}}><GraduationCap/></span><h3>Bắt đầu lộ trình đầu tiên</h3><p className="muted">Bạn chưa sở hữu khóa học nào.</p><Link href="/courses" className="btn btn-primary">Khám phá khóa học</Link></div>:all.map(e=>{const first=e.course.sections.flatMap(s=>s.lessons)[0];return <article className="card" style={{padding:28,display:"grid",gridTemplateColumns:"auto 1fr auto",gap:24,alignItems:"center"}} key={e.id}><span className="icon-box" style={{width:62,height:62}}><BookOpenCheck/></span><div><div style={{display:"flex",alignItems:"center",gap:10}}><span className="badge">{e.status==="COMPLETED"?"Hoàn thành":"Đang học"}</span><span className="muted" style={{fontSize:12}}><Clock3 size={13} style={{display:"inline"}}/> Đã học {e.completed}/{e.total} bài</span></div><h2 style={{margin:"12px 0 15px",fontSize:22}}>{e.course.title}</h2><div style={{height:10,background:"#e4eee9",borderRadius:99,overflow:"hidden"}}><div style={{width:`${e.percent}%`,height:"100%",borderRadius:99,background:"linear-gradient(90deg,var(--emerald),var(--emerald-light))",transition:"width .5s ease"}}/></div><p className="muted" style={{fontSize:12,marginBottom:0}}>{e.percent}% hoàn thành</p></div>{first&&<Link className="btn btn-primary" href={`/learn/${e.course.slug}/${first.id}`}>Tiếp tục <ArrowRight size={16}/></Link>}</article>})}</div></div></section></main>
}
