"use client";
import { useRouter } from "next/navigation"; import { useState } from "react";
export function LogoutButton(){const router=useRouter();return <button className="btn btn-outline" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});router.push("/");router.refresh()}}>Đăng xuất</button>}
export function AuthForm({mode}:{mode:"login"|"register"}){const router=useRouter();const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form);const res=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();setLoading(false);if(!res.ok)return setError(data.error||"Có lỗi xảy ra");router.push(mode==="login"?"/my-courses":"/login?registered=1");router.refresh()}return <form onSubmit={submit} style={{display:"grid",gap:16}}>{mode==="register"&&<><Field name="name" label="Họ và tên"/><Field name="phone" label="Số điện thoại" type="tel"/></>}<Field name="email" label="Email" type="email"/><Field name="password" label="Mật khẩu" type="password"/>{mode==="register"&&<Field name="confirmPassword" label="Xác nhận mật khẩu" type="password"/>}{error&&<p style={{color:"#dc2626",margin:0}}>{error}</p>}<button className="btn btn-primary" disabled={loading}>{loading?"Đang xử lý...":mode==="login"?"Đăng nhập":"Tạo tài khoản"}</button></form>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label><span className="label">{label}</span><input className="input" name={name} type={type} required minLength={type==="password"?8:undefined}/></label>}
export function BuyButton({courseId,owned,free}:{courseId:string;owned:boolean;free:boolean}){const router=useRouter();const [busy,setBusy]=useState(false);if(owned)return <button className="btn btn-primary" onClick={()=>router.push("/my-courses")}>Vào học</button>;return <button className="btn btn-primary" disabled={busy} onClick={async()=>{setBusy(true);const r=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId})});if(r.status===401)return router.push("/login");const d=await r.json();if(r.ok)router.push(free?"/my-courses":`/checkout/${d.orderCode}`);else alert(d.error);setBusy(false)}}>{busy?"Đang xử lý...":free?"Đăng ký miễn phí":"Liên hệ đăng ký qua Zalo"}</button>}
export function ProgressButton({lessonId,completed}:{lessonId:string;completed:boolean}){const router=useRouter();const [busy,setBusy]=useState(false);return <button className="btn btn-primary" disabled={busy} onClick={async()=>{setBusy(true);await fetch("/api/progress",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lessonId,completed:!completed})});router.refresh();setBusy(false)}}>{completed?"Đã hoàn thành ✓":"Đánh dấu hoàn thành"}</button>}
export function OrderAction({id,action}:{id:string;action:"confirm"|"cancel"}){const router=useRouter();return <button className={`btn ${action==="confirm"?"btn-primary":"btn-danger"}`} onClick={async()=>{if(!confirm(action==="confirm"?"Xác nhận và mở khóa học cho học viên này?":"Hủy yêu cầu đăng ký này?"))return;const r=await fetch(`/api/admin/orders/${id}/${action}`,{method:"POST"});if(!r.ok)alert((await r.json()).error);router.refresh()}}>{action==="confirm"?"Mở khóa học":"Hủy yêu cầu"}</button>}
export function CourseCodeEditor({id,current}:{id:string;current:string|null}){const router=useRouter();const[value,setValue]=useState(current||"");const[busy,setBusy]=useState(false);return <form className="course-code-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await fetch(`/api/admin/courses/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({courseCode:value.trim().toUpperCase()})});setBusy(false);if(!r.ok)return alert((await r.json()).error||"Không thể lưu mã khóa học");router.refresh()}}><input className="input" aria-label="Mã khóa học" value={value} onChange={e=>setValue(e.target.value.toUpperCase())} pattern="[A-Za-z0-9-]+" required/><button className="btn btn-primary" disabled={busy}>{busy?"Đang lưu":"Lưu"}</button></form>}
